# Docker Compose Override for Development
# This file is automatically loaded alongside docker-compose.yml
# Perfect for development-specific configurations

version: '3.8'

services:
  app:
    # Override build target for development
    build:
      target: development
    # Enable hot reloading
    command: >
      sh -c "
        mkdir -p /app/cache /app/data /app/models &&
        echo '{}' > /app/cache/corpus_stats.json &&
        echo '{}' > /app/cache/corpus_features.json &&
        touch /app/data/words_with_freqs.json &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
      "
    environment:
      # Development environment variables
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      # Additional development volumes
      - .:/app:delegated
      - /app/__pycache__
      - /app/.pytest_cache
    # Port mapping for development debugging
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy port if needed

  redis:
    # Development Redis configuration
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    # Enable Redis CLI access
    ports:
      - "6379:6379"